name: CS224W_env
channels:
  - pytorch       # Priority channel for PyTorch-related packages
  - conda-forge   # Broad selection of packages with frequent updates
  - bioconda      # Bioinformatics packages
  - defaults      # Fallback for core packages

dependencies:
  - python=3.10
  - cudatoolkit=11.8            # CUDA version compatible with PyTorch 2.4.0
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.10.1
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - networkx=3.3
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - dask=2024.10.0


  # PyTorch and related packages
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0

  # Additional packages as per previous requirements
  - cooler=0.9.3
  - h5py=3.12.1
  - seaborn=0.12.2
  - tqdm=4.66.1

  # torch-geometric and dependencies handled via pip
  - pip:
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2 -f https://pytorch-geometric.com/whl/torch-2.4.0.html
      - torch-sparse==0.6.18 -f https://pytorch-geometric.com/whl/torch-2.4.0.html
      - torch-cluster -f https://pytorch-geometric.com/whl/torch-2.4.0.html
      - torch-spline-conv -f https://pytorch-geometric.com/whl/torch-2.4.0.html
      - tangermeme==0.4.1
      - bpnet-lite
